version: '3.3'
services:
  db:
    image: postgres:12.4
    volumes:
      - var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    build:
#    image: timaone2014/foodgram:latest
      context: ../backend/foodgram
    volumes:
      - ../static/:/app/static/
      - ./media/:/app/media/recipes/
    depends_on:
      - db
    env_file:
      - ./.env
    restart: always

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
#    image: timaone2014/foodgram_frontend:v1
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - ../static/:/var/html/static/
      - ../media/:/var/html/media/
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  postgres_data:
  static_value:
  media_value:
