# Generated by Django 2.2.16 on 2022-08-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220714_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Название рецепта'),
        ),
    ]
